
create database music_streamingDB;
go

use music_streamingDB;
go

-- 1. ROLES
CREATE TABLE ROLES (
    role_id INT IDENTITY(1,1) PRIMARY KEY,
    role_name VARCHAR(50) NOT NULL, -- admin/user/moderator
    permissions VARCHAR(255)
);

-- 2. USERS
CREATE TABLE USERS (
    user_id INT IDENTITY(1,1) PRIMARY KEY,
    username NVARCHAR(100) UNIQUE NOT NULL,
    email NVARCHAR(100) UNIQUE NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    avatar_url NVARCHAR(255),
    created_at DATETIME DEFAULT GETDATE(),
    role_id INT FOREIGN KEY REFERENCES ROLES(role_id)
);

-- 3. SUBSCRIPTION_PLANS
CREATE TABLE SUBSCRIPTION_PLANS (
    plan_id INT IDENTITY(1,1) PRIMARY KEY,
    plan_name VARCHAR(100) NOT NULL,
    price DECIMAL(10,2) NOT NULL CHECK (price >= 0),
    duration_months INT NOT NULL CHECK (duration_months > 0),
    ad_free BIT NOT NULL DEFAULT 0,
    high_quality_audio BIT NOT NULL DEFAULT 0,
    max_downloads INT NOT NULL DEFAULT 0 CHECK (max_downloads >= 0)
);

-- 4. USER_SUBSCRIPTIONS
CREATE TABLE USER_SUBSCRIPTIONS (
    subscription_id INT IDENTITY(1,1) PRIMARY KEY,
    user_id INT NOT NULL FOREIGN KEY REFERENCES USERS(user_id) ON DELETE CASCADE,
    plan_id INT NOT NULL FOREIGN KEY REFERENCES SUBSCRIPTION_PLANS(plan_id),
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    status VARCHAR(50) NOT NULL CHECK (status IN ('active', 'expired', 'cancelled', 'paused')),
    auto_renew BIT NOT NULL DEFAULT 0
);

-- 5. PAYMENTS
CREATE TABLE PAYMENTS (
    payment_id INT IDENTITY(1,1) PRIMARY KEY,
    subscription_id INT NOT NULL FOREIGN KEY REFERENCES USER_SUBSCRIPTIONS(subscription_id) ON DELETE CASCADE,
    amount DECIMAL(10,2) NOT NULL CHECK (amount > 0),
    payment_date DATETIME DEFAULT GETDATE(),
    status VARCHAR(50) NOT NULL CHECK (status IN ('pending', 'completed', 'failed', 'refunded')),
    transaction_id VARCHAR(100) UNIQUE
);

-- 6. ARTISTS
CREATE TABLE ARTISTS (
    artist_id INT IDENTITY(1,1) PRIMARY KEY,
    name NVARCHAR(255) NOT NULL,
    country NVARCHAR(100),
    bio NVARCHAR(MAX),
    cover_image_url VARCHAR(255)
);

-- 7. ALBUMS
CREATE TABLE ALBUMS (
    album_id INT IDENTITY(1,1) PRIMARY KEY,
    title NVARCHAR(255) NOT NULL,
    artist_id INT FOREIGN KEY REFERENCES ARTISTS(artist_id),
    release_year INT,
    cover_image_url VARCHAR(255),
    record_label NVARCHAR(255)
);

-- 8. SONGS
CREATE TABLE SONGS (
    song_id INT IDENTITY(1,1) PRIMARY KEY,
    name NVARCHAR(255) NOT NULL,
    album_id INT FOREIGN KEY REFERENCES ALBUMS(album_id) ON DELETE SET NULL,
    duration INT NOT NULL CHECK (duration > 0),
    file_path VARCHAR(255) UNIQUE NOT NULL,
    lyrics NVARCHAR(MAX),
    uploaded_at DATETIME DEFAULT GETDATE()
);

-- 9. SONG_ARTISTS (N-N)
DROP TABLE IF EXISTS SONG_ARTISTS;
CREATE TABLE SONG_ARTISTS (
	id INT IDENTITY(1,1) PRIMARY KEY,
    song_id INT FOREIGN KEY REFERENCES SONGS(song_id) ON DELETE CASCADE,
    artist_id INT FOREIGN KEY REFERENCES ARTISTS(artist_id) ON DELETE CASCADE,
    role VARCHAR(50) NOT NULL
);

-- 10. GENRES
CREATE TABLE GENRES (
    genre_id INT IDENTITY(1,1) PRIMARY KEY,
    genre_name NVARCHAR(100) UNIQUE NOT NULL,
    description NVARCHAR(500)
);

-- 11. SONG_GENRES (N-N)
CREATE TABLE SONG_GENRES (
    id INT IDENTITY(1,1) PRIMARY KEY,
    song_id INT NOT NULL FOREIGN KEY REFERENCES SONGS(song_id) ON DELETE CASCADE,
    genre_id INT NOT NULL FOREIGN KEY REFERENCES GENRES(genre_id) ON DELETE CASCADE,
    UNIQUE (song_id, genre_id)
);

-- 12. PLAYLISTS
CREATE TABLE PLAYLISTS (
    playlist_id INT IDENTITY(1,1) PRIMARY KEY,
    user_id INT NOT NULL FOREIGN KEY REFERENCES USERS(user_id) ON DELETE CASCADE,
    name NVARCHAR(255) NOT NULL,
    description NVARCHAR(MAX),
    is_public BIT NOT NULL DEFAULT 1,
    created_at DATETIME DEFAULT GETDATE(),
    updated_at DATETIME DEFAULT GETDATE()
);

-- 13. PLAYLIST_SONGS (N-N)
CREATE TABLE PLAYLIST_SONGS (
    id INT IDENTITY(1,1) PRIMARY KEY,
    playlist_id INT NOT NULL FOREIGN KEY REFERENCES PLAYLISTS(playlist_id) ON DELETE CASCADE,
    song_id INT NOT NULL FOREIGN KEY REFERENCES SONGS(song_id) ON DELETE CASCADE,
    position INT NOT NULL CHECK (position > 0),
    added_at DATETIME DEFAULT GETDATE(),
    UNIQUE (playlist_id, song_id)
);

-- 14. SONG_COMMENTS
CREATE TABLE SONG_COMMENTS (
    comment_id INT IDENTITY(1,1) PRIMARY KEY,
    user_id INT NOT NULL FOREIGN KEY REFERENCES USERS(user_id) ON DELETE CASCADE,
    song_id INT NOT NULL FOREIGN KEY REFERENCES SONGS(song_id) ON DELETE CASCADE,
    comment_text NVARCHAR(MAX) NOT NULL,
    timestamp_position INT CHECK (timestamp_position >= 0),
    created_at DATETIME DEFAULT GETDATE()
);

-- 15. COMMENT_LIKES
CREATE TABLE COMMENT_LIKES (
    id INT IDENTITY(1,1) PRIMARY KEY,
    user_id INT NOT NULL FOREIGN KEY REFERENCES USERS(user_id) ON DELETE NO ACTION,
    comment_id INT NOT NULL FOREIGN KEY REFERENCES SONG_COMMENTS(comment_id) ON DELETE CASCADE,
    liked_at DATETIME DEFAULT GETDATE(),
    UNIQUE (user_id, comment_id)
);

-- 16. SONG_LIKES
CREATE TABLE SONG_LIKES (
    id INT IDENTITY(1,1) PRIMARY KEY,
    user_id INT NOT NULL FOREIGN KEY REFERENCES USERS(user_id) ON DELETE CASCADE,
    song_id INT NOT NULL FOREIGN KEY REFERENCES SONGS(song_id) ON DELETE CASCADE,
    liked_at DATETIME DEFAULT GETDATE(),
    UNIQUE (user_id, song_id)
);
GO

-- 17. USER_SONGS (listen history)
CREATE TABLE USER_SONGS (
    listen_id INT IDENTITY(1,1) PRIMARY KEY,
    user_id INT NOT NULL FOREIGN KEY REFERENCES USERS(user_id) ON DELETE CASCADE,
    song_id INT NOT NULL FOREIGN KEY REFERENCES SONGS(song_id) ON DELETE CASCADE,
    listened_at DATETIME DEFAULT GETDATE()
);
GO

CREATE INDEX IX_USER_SONGS_song_date ON USER_SONGS(song_id, listened_at);

CREATE INDEX IX_USER_SONGS_user_id  ON USER_SONGS(user_id);

CREATE INDEX IX_SONG_LIKES_song_id ON SONG_LIKES(song_id);

CREATE INDEX IX_PAYMENTS_subscription_id ON PAYMENTS(subscription_id);

CREATE INDEX IX_SONG_ARTISTS_song_id ON SONG_ARTISTS(song_id);

CREATE INDEX IX_SONG_GENRES_song_id ON SONG_GENRES(song_id);

CREATE NONCLUSTERED INDEX IX_USERS_username ON USERS (username);

CREATE NONCLUSTERED INDEX IX_SONG_COMMENTS_userid ON SONG_COMMENTS (user_id);

CREATE NONCLUSTERED INDEX IX_USER_SONGS_listened_at
ON USER_SONGS (listened_at) INCLUDE (user_id);

CREATE NONCLUSTERED INDEX IX_SONG_COMMENTS_songid_timestamp
ON SONG_COMMENTS (song_id, timestamp_position)
INCLUDE (user_id, comment_text, created_at); 

CREATE NONCLUSTERED INDEX IX_COMMENT_LIKES_commentid
ON COMMENT_LIKES (comment_id)
INCLUDE (liked_at);


CREATE INDEX IX_ARTISTS_name ON ARTISTS(name);

CREATE INDEX IX_SONG_ARTISTS_artist_song ON SONG_ARTISTS(artist_id, song_id); 

CREATE INDEX IX_GENRES_Name ON GENRES(genre_name);

CREATE INDEX IX_USER_SUBS_Status_EndDate ON USER_SUBSCRIPTIONS(status, end_date);

CREATE INDEX IX_SUB_PLANS_Name ON SUBSCRIPTION_PLANS(plan_name);

CREATE INDEX IX_PAYMENTS_Status_Date ON PAYMENTS(status, payment_date);


CREATE NONCLUSTERED INDEX IX_Songs_AlbumId ON SONGS(album_id);

CREATE NONCLUSTERED INDEX IX_Playlists_UserId 
ON PLAYLISTS(user_id) 
INCLUDE (name, description, is_public, created_at);

CREATE NONCLUSTERED INDEX IX_SongArtists_Song_Role ON SONG_ARTISTS(song_id, role);

CREATE NONCLUSTERED INDEX IX_SongGenres_GenreId 
ON SONG_GENRES(genre_id);

CREATE NONCLUSTERED INDEX IX_SongComments_Song_Created 
ON SONG_COMMENTS(song_id ASC, created_at DESC);

CREATE NONCLUSTERED INDEX IDX_Songs_Name ON SONGS(name);

CREATE NONCLUSTERED INDEX IDX_Songs_Duration_Desc ON SONGS(duration DESC);

-- IDX_Artists_Name removed: duplicate of IX_ARTISTS_name (line 199)

CREATE NONCLUSTERED INDEX IDX_Albums_ArtistId ON ALBUMS(artist_id);

-- IDX_Songs_AlbumId removed: duplicate of IX_Songs_AlbumId (line 212)
